# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='msg_arena.proto',
  package='',
  serialized_pb='\n\x0fmsg_arena.proto\"\x1b\n\nArenaEnded\x12\r\n\x05\x65rror\x18\x04 \x01(\tB\x0b\n\tproto.msg')




_ARENAENDED = descriptor.Descriptor(
  name='ArenaEnded',
  full_name='ArenaEnded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='error', full_name='ArenaEnded.error', index=0,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=46,
)



class ArenaEnded(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ARENAENDED
  
  # @@protoc_insertion_point(class_scope:ArenaEnded)

# @@protoc_insertion_point(module_scope)
